# Generated by Django 5.0.1 on 2024-01-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('test_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('screenshot_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
